#!/bin/sh

#mutt

#mkdir -p $HOME/.getmail
#ln -s $HOME/szc_life/configure/rc.avonaco $HOME/.getmail/rc.avonaco
#ln -s $HOME/szc_life/configure/rc.yahoo $HOME/.getmail/rc.yahoo


stow -t $HOME bash

#stow -t $HOME mutt
stow -t $HOME vim

mkdir -p $HOME/.xmonad
stow -t $HOME --no-folding  xmonad

mkdir -p $HOME/.emacs.d
stow -t $HOME --no-folding emacs


stow -t $HOME xorg
stow -t / zhengma

#stow -t $HOME taskjuggler
stow -t $HOME procmail

systemctl enable systemd-timesyncd.service

